/**
 * Loader for the committed hero run.
 *
 * `config/runs/hero.json` is the floor of the degradation ladder: a full result
 * set checked into the repository so that with no network, no database and no
 * API key the board still renders correctly. ARCHITECTURE.md section 10.
 *
 * It is generated by `npm run gauntlet -- --write-hero` from a real run, never
 * hand-authored, so nothing on the page is a number nobody computed.
 */

import type { AttackOnUsRow, BoardCell, Decision, Finding } from '../contracts/types';

export interface HeroRun {
  runId: string;
  generatedAt: string;
  scorecardVersion: string;
  checksVersion: string;
  pricingVersion: string;
  cells: BoardCell[];
  attacksOnUs: AttackOnUsRow[];
  /** The primed first-visitor scene: one merchant, one purchase, resolved. */
  primed: {
    merchantId: string;
    display: string;
    mode: string;
    amountMinor: number;
    currency: string;
    purpose: string;
    decision: Decision;
    /** Replayed in order on the landing page, with their real latencies. */
    timeline: Array<{ atMs: number; finding: Finding }>;
    totalLatencyMs: number;
  } | null;
  ledger: {
    fundCapitalMinor: number;
    feesCollectedMinor: number;
    collateralHeldMinor: number;
    payoutsMinor: number;
    balanced: boolean;
  } | null;
}

let cached: HeroRun | null | undefined;

export function loadHeroRun(): HeroRun | null {
  if (cached !== undefined) return cached;
  try {
    // Static import path so the bundler includes it in the serverless output.
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const data = require('../../config/runs/hero.json') as HeroRun;
    cached = data && Array.isArray(data.cells) ? data : null;
  } catch {
    cached = null;
  }
  return cached;
}
